offboard_control:
    ros__parameters:
      debug: true
      test: 0
      MotionStart: 5.0
      Tmotion: 5.0
      Trest: 1.0
#      StartingPoint: [3.52, 5.61, -0.87]
      StartingPoint: [1.0, 1.0, -1.0]
      deltaX: 2.0
      deltaY: 2.0
      deltaZ: 0.2