offboard_control:
    ros__parameters:
      debug: true

      # Square test
      test: 0
      MotionStart: 15.0
      Tmotion: 10.0
      Trest: 10.0
      StartingPoint: [3.61, 1.03, -0.8]
      yaw: 1.57
      deltaX: 1.8
      deltaY: 1.8

      # # Step test
      # test: 1
      # MotionStart: 20.0
      # Tmotion: 10.0
      # Trest: 10.0
      # StartingPoint: [1.41, 2.07, -0.7]   
      # yaw: 1.57   
      # deltaZ: 0.3

      # # Hovering test
      # test: 2
      # MotionStart: 15.0
      # Tmotion: 5.0
      # Trest: 5.0
      # StartingPoint: [2.41, 4.9, -0.8]   
      # yaw: -180.0   
      # deltaZ: 0.4
